nohup: ignoring input
/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2022-05-31 14:15:51,050: INFO/MainProcess] beat: Starting...
[2022-05-31 14:15:51,402: INFO/MainProcess] DatabaseScheduler: Schedule changed.
[2022-05-31 14:15:51,583: INFO/MainProcess] Scheduler: Sending due task SURYA-API-9_30-AM (master.task.Surya_api)
[2022-05-31 14:15:52,696: ERROR/MainProcess] Message Error: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
['  File "/home/tspl45/Desktop/GPI_env/bin/celery", line 8, in <module>\n    sys.exit(main())\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/__main__.py", line 15, in main\n    sys.exit(_main())\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bin/celery.py", line 217, in main\n    return celery(auto_envvar_prefix="CELERY")\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__\n    return self.main(*args, **kwargs)\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1053, in main\n    rv = self.invoke(ctx)\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 754, in invoke\n    return __callback(*args, **kwargs)\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func\n    return f(get_current_context(), *args, **kwargs)\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bin/base.py", line 134, in caller\n    return f(ctx, *args, **kwargs)\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bin/beat.py", line 72, in beat\n    return beat().run()\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/apps/beat.py", line 77, in run\n    self.start_scheduler()\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/apps/beat.py", line 105, in start_scheduler\n    service.start()\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/beat.py", line 645, in start\n    interval = self.scheduler.tick()\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/beat.py", line 357, in tick\n    self.apply_entry(entry, producer=self.producer)\n', '  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/beat.py", line 290, in apply_entry\n    exc, traceback.format_stack(), exc_info=True)\n']
Traceback (most recent call last):
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/beat.py", line 287, in apply_entry
    result = self.apply_async(entry, producer=producer, advance=False)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/beat.py", line 418, in apply_async
    self._do_sync()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/beat.py", line 430, in _do_sync
    self.sync()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 301, in sync
    self.schedule[name].save()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django_celery_beat/schedulers.py", line 164, in save
    obj.save()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django_celery_beat/models.py", line 581, in save
    super().save(*args, **kwargs)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
[2022-05-31 14:16:00,030: INFO/MainProcess] Task master.task.Surya_api[4e837305-4e4e-4e30-a73e-e6afe049faf2] received
[2022-05-31 14:16:24,677: WARNING/ForkPoolWorker-1] surya_data
[2022-05-31 14:16:24,677: WARNING/ForkPoolWorker-1]  
[2022-05-31 14:16:24,678: WARNING/ForkPoolWorker-1] https://ss.godfreyphillips.co/api/api/GPIInterface?Passcode=GP!W!N
[2022-05-31 14:16:24,678: WARNING/ForkPoolWorker-1]  
[2022-05-31 14:16:24,678: WARNING/ForkPoolWorker-1] ======surya_data ======
[2022-05-31 14:16:26,064: WARNING/ForkPoolWorker-1] =======update===
[2022-05-31 14:16:26,225: WARNING/ForkPoolWorker-1] =======update===
[2022-05-31 14:16:26,865: WARNING/ForkPoolWorker-1] =======update===
[2022-05-31 14:16:29,318: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:30,970: WARNING/ForkPoolWorker-1] =======update===
[2022-05-31 14:16:31,295: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:31,511: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:31,730: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:31,947: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:32,184: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:32,411: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:32,638: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:32,858: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:33,091: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:33,314: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:33,542: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:33,766: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:33,983: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:34,248: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:34,470: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:34,893: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:35,030: WARNING/ForkPoolWorker-1] =======update===
[2022-05-31 14:16:35,251: WARNING/ForkPoolWorker-1] =====create====
[2022-05-31 14:16:3[2022-05-31 14:18:57,373: CRITICAL/MainProcess] beat raised exception <class 'ValueError'>: ValueError('MySQL backend does not support timezone-aware datetimes when USE_TZ is False.')
Traceback (most recent call last):
  File "/homeUnicodeDecodeError('ascii', b'\xc2\x96\xac\xb3\n+w]\xb7', 0, 1, 'ordinal not in range(128)')
"POST /api/v1/login/ HTTP/1.1" 200 158
Error('Incorrect padding')
"POST /api/v1/login/ HTTP/1.1" 200 86
UnicodeDecodeError('ascii', b'\xc2\x96\xac\xb3\n+w]\xb7', 0, 1, 'ordinal not in range(128)')
"POST /api/v1/login/ HTTP/1.1" 200 158
UnicodeDecodeError('ascii', b'\xc2\x96\xac\xb3\n+w]\xb7', 0, 1, 'ordinal not in range(128)')
"POST /api/v1/login/ HTTP/1.1" 200 158
UnicodeDecodeError('ascii', b'\xc2\x96\xac\xb3\n+w]\xb7', 0, 1, 'ordinal not in range(128)')
"POST /api/v1/login/ HTTP/1.1" 200 158
Unauthorized: /api/v1/profile/
"GET /api/v1/profile/ HTTP/1.1" 401 183
Starting Scheduler ...
Starting Scheduler ...
e-packages/django_celery_beat/models.py", line 581, in save
    super().save(*args, **kwargs)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/base.py", line 845, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/base.py", line 899, in _do_update
    return filtered._update(values) > 0
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/backends/mysql/compiler.py", line 44, in as_sql
    update_query, update_params = super().as_sql()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1525, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1428, in get_db_prep_value
    return connection.ops.adapt_datetimefield_value(value)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 253, in adapt_datetimefield_value
    raise ValueError("MySQL backend does not support timezone-aware datetimes when USE_TZ is False.")
ValueError: MySQL backend does not support timezone-aware datetimes when USE_TZ is False.
[2022-05-31 14:18:57,374: WARNING/MainProcess] Traceback (most recent call last):
[2022-05-31 14:18:57,374: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/bin/celery", line 8, in <module>
[2022-05-31 14:18:57,374: WARNING/MainProcess]     
[2022-05-31 14:18:57,374: WARNING/MainProcess] sys.exit(main())
[2022-05-31 14:18:57,374: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/__main__.py", line 15, in main
[2022-05-31 14:18:57,375: WARNING/MainProcess]     
[2022-05-31 14:18:57,375: WARNING/MainProcess] sys.exit(_main())
[2022-05-31 14:18:57,375: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bin/celery.py", line 217, in main
[2022-05-31 14:18:57,375: WARNING/MainProcess]     
[2022-05-31 14:18:57,375: WARNING/MainProcess] return celery(auto_envvar_prefix="CELERY")
[2022-05-31 14:18:57,375: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
[2022-05-31 14:18:57,376: WARNING/MainProcess]     
[2022-05-31 14:18:57,376: WARNING/MainProcess] return self.main(*args, **kwargs)
[2022-05-31 14:18:57,376: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1053, in main
[2022-05-31 14:18:57,377: WARNING/MainProcess]     
[2022-05-31 14:18:57,377: WARNING/MainProcess] rv = self.invoke(ctx)
[2022-05-31 14:18:57,377: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
[2022-05-31 14:18:57,377: WARNING/MainProcess]     
[2022-05-31 14:18:57,378: WARNING/MainProcess] return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-05-31 14:18:57,378: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
[2022-05-31 14:18:57,378: WARNING/MainProcess]     
[2022-05-31 14:18:57,378: WARNING/MainProcess] return ctx.invoke(self.callback, **ctx.params)
[2022-05-31 14:18:57,379: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
[2022-05-31 14:18:57,379: WARNING/MainProcess]     
[2022-05-31 14:18:57,379: WARNING/MainProcess] return __callback(*args, **kwargs)
[2022-05-31 14:18:57,379: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
[2022-05-31 14:18:57,379: WARNING/MainProcess]     
[2022-05-31 14:18:57,379: WARNING/MainProcess] return f(get_current_context(), *args, **kwargs)
[2022-05-31 14:18:57,380: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bin/base.py", line 134, in caller
[2022-05-31 14:18:57,380: WARNING/MainProcess]     
[2022-05-31 14:18:57,380: WARNING/MainProcess] return f(ctx, *args, **kwargs)
[2022-05-31 14:18:57,380: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bin/beat.py", line 72, in beat
[2022-05-31 14:18:57,380: WARNING/MainProcess]     
[2022-05-31 14:18:57,380: WARNING/MainProcess] return beat().run()
[2022-05-31 14:18:57,381: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/apps/beat.py", line 77, in run
[2022-05-31 14:18:57,381: WARNING/MainProcess]     
[2022-05-31 14:18:57,381: WARNING/MainProcess] self.start_scheduler()
[2022-05-31 14:18:57,381: WARNING/MainProcess]   File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/apps/beat.py", line 105, in start_scheduler
[2022-05-31 14:18
Restarting celery worker (/home/tspl45/Desktop/GPI_env/bin/celery -A secondary_sales.celery worker -l INFO)
[2022-05-31 14:21:45,445: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:24191 exited with 'exitcode 70'
[2022-05-31 14:21:45,455: ERROR/MainProcess] Process 'ForkPoolWorker-3' pid:24190 exited with 'exitcode 70'
[2022-05-31 14:21:45,466: ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:24189 exited with 'exitcode 70'
[2022-05-31 14:21:45,476: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:24188 exited with 'exitcode 70'
[2022-05-31 14:21:45,489: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: exitcode 70 Job: 0.')
Traceback (most recent call last):
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 628, in start
    c.loop(*c.loop_args())
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/worker/loops.py", line 86, in asynloop
    state.maybe_shutdown()
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/worker/state.py", line 89, in maybe_shutdown
    raise WorkerShutdown(should_stop)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: exitcode 70 Job: 0.
/home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Adding job tentatively -- it will be properly scheduled when the scheduler starts
Starting Scheduler ...
Starting Scheduler ...
 
 -------------- celery@tspl45-desktop v5.2.6 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.13.0-44-generic-x86_64-with-glibc2.29 2022-05-31 14:21:48
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         secondary_sales:0x7fb56da68e50
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . master.task.Sfa_api
  . master.task.Surya_api
  . secondary_sales.celery.debug_task

[2022-05-31 14:21:48,279: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-05-31 14:21:48,280: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-05-31 14:21:48,280: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-05-31 14:21:48,280: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ACCEPT_CONTENT' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the accept_content instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-05-31 14:21:48,280: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-05-31 14:21:48,280: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-05-31 14:21:48,280: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_IMPORTS' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the imports instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-05-31 14:21:48,280: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-05-31 14:21:48,629: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-05-31 14:21:48,633: INFO/MainProcess] mingle: searching for neighbors
[2022-05-31 14:21:49,640: INFO/MainProcess] mingle: all alone
[2022-05-31 14:21:49,663: WARNING/MainProcess] /home/tspl45/Desktop/GPI_env/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-05-31 14:21:49,664: INFO/MainProcess] celery@tspl45-desktop ready.
[2022-05-31 14:30:40,172: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:24437 exited with 'signal 9 (SIGKILL)'
